<?xml version="1.0"?>
<xsl:stylesheed version="1.0" xmlns="http://www.w3.org/1999/XSL/Trasform"
<xsl:template match="biblioteca">

<html>
    <body>
        <h2>Mi biblioteca</h2>
        <table border="1">
            <tr>
                <th>titulo</th>
                <th>autor</th>
                <th>Editorial</th>
                <th>año</th>
            <tr>
                
<!--plantillas de trasformacion-->
</xsl:stylesheed>